<?php 
# Code generated by sdkgen
# Generated on 2019-10-01 20:26:16.0055947 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!
namespace Vendasta\AccountGroup\V1\internal;

use Vendasta\AccountGroup\V1\Config;

class AccountGroupServiceGeneratedClient
{
    private $transport;
    
    /**
     * AccountGroupServiceGeneratedClient constructor.
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     */
    public function __construct(string $env, float $default_timeout = 10000)
    {
        $this->transport = $this->getTransportClient($env, $default_timeout);
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     * @return AccountGroupServiceClientInterface
     */
    private function getTransportClient(string $env, float $default_timeout = 10000): AccountGroupServiceClientInterface
    {
        $config = $this->getEnvConfig($env);

        if (class_exists('Grpc\ChannelCredentials', true)) {
            return new AccountGroupServiceGRPCClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        } else {
            return new AccountGroupServiceHTTPClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        }
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @return array
     */
    private function getEnvConfig(string $env): array {
        return Config::ENVIRONMENT_PARAMS[$env];
    }
    
    /**
     * @param \Accountgroup\V1\GetMultiRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\GetMultiResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetMulti(\Accountgroup\V1\GetMultiRequest $req, array $options = []): \Accountgroup\V1\GetMultiResponse
    {
        return $this->transport->GetMulti($req, $options);
    }
    
    /**
     * @param \Accountgroup\V1\LookupRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\PagedResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Lookup(\Accountgroup\V1\LookupRequest $req, array $options = []): \Accountgroup\V1\PagedResponse
    {
        return $this->transport->Lookup($req, $options);
    }
    
    /**
     * @param \Accountgroup\V1\CreateAccountGroupRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\CreateAccountGroupResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Create(\Accountgroup\V1\CreateAccountGroupRequest $req, array $options = []): \Accountgroup\V1\CreateAccountGroupResponse
    {
        return $this->transport->Create($req, $options);
    }
    
    /**
     * @param \Accountgroup\V1\DeleteAccountGroupRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Delete(\Accountgroup\V1\DeleteAccountGroupRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->Delete($req, $options);
    }
    
    /**
     * @param \Accountgroup\V1\BulkUpdateRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function BulkUpdate(\Accountgroup\V1\BulkUpdateRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->BulkUpdate($req, $options);
    }
    
    /**
     * @param \Accountgroup\V1\ListRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\PagedResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function List(\Accountgroup\V1\ListRequest $req, array $options = []): \Accountgroup\V1\PagedResponse
    {
        return $this->transport->List($req, $options);
    }
    
    /**
     * @param \Accountgroup\V1\ListPotentialDuplicatesRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\ListPotentialDuplicatesResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListPotentialDuplicates(\Accountgroup\V1\ListPotentialDuplicatesRequest $req, array $options = []): \Accountgroup\V1\ListPotentialDuplicatesResponse
    {
        return $this->transport->ListPotentialDuplicates($req, $options);
    }
    
    /**
     * @param \Accountgroup\V1\ListAllPotentialDuplicatesRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\ListAllPotentialDuplicatesResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListAllPotentialDuplicates(\Accountgroup\V1\ListAllPotentialDuplicatesRequest $req, array $options = []): \Accountgroup\V1\ListAllPotentialDuplicatesResponse
    {
        return $this->transport->ListAllPotentialDuplicates($req, $options);
    }
    
}
