<?php 
# Code generated by sdkgen
# Generated on 2019-10-01 20:26:16.0055947 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!

namespace Vendasta\AccountGroup\V1\internal;

interface AccountGroupServiceClientInterface
{ 
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::GetMulti
     * @param \Accountgroup\V1\GetMultiRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\GetMultiResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetMulti(\Accountgroup\V1\GetMultiRequest $req, array $options = []): \Accountgroup\V1\GetMultiResponse;
    
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::Lookup
     * @param \Accountgroup\V1\LookupRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\PagedResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Lookup(\Accountgroup\V1\LookupRequest $req, array $options = []): \Accountgroup\V1\PagedResponse;
    
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::Create
     * @param \Accountgroup\V1\CreateAccountGroupRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\CreateAccountGroupResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Create(\Accountgroup\V1\CreateAccountGroupRequest $req, array $options = []): \Accountgroup\V1\CreateAccountGroupResponse;
    
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::Delete
     * @param \Accountgroup\V1\DeleteAccountGroupRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Delete(\Accountgroup\V1\DeleteAccountGroupRequest $req, array $options = []): \Google\Protobuf\GPBEmpty;
    
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::BulkUpdate
     * @param \Accountgroup\V1\BulkUpdateRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function BulkUpdate(\Accountgroup\V1\BulkUpdateRequest $req, array $options = []): \Google\Protobuf\GPBEmpty;
    
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::List
     * @param \Accountgroup\V1\ListRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\PagedResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function List(\Accountgroup\V1\ListRequest $req, array $options = []): \Accountgroup\V1\PagedResponse;
    
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::ListPotentialDuplicates
     * @param \Accountgroup\V1\ListPotentialDuplicatesRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\ListPotentialDuplicatesResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListPotentialDuplicates(\Accountgroup\V1\ListPotentialDuplicatesRequest $req, array $options = []): \Accountgroup\V1\ListPotentialDuplicatesResponse;
    
    /**
     * Auth wrapper for \AccountGroup\V1\AccountGroupServiceClient::ListAllPotentialDuplicates
     * @param \Accountgroup\V1\ListAllPotentialDuplicatesRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Accountgroup\V1\ListAllPotentialDuplicatesResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function ListAllPotentialDuplicates(\Accountgroup\V1\ListAllPotentialDuplicatesRequest $req, array $options = []): \Accountgroup\V1\ListAllPotentialDuplicatesResponse;
    
}
